const nodemailer = require('nodemailer');

let transporter = null;

const initEmailTransporter = async () => {
    try {
        if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
            // Optional custom SMTP
            transporter = nodemailer.createTransport({
                host: process.env.SMTP_HOST,
                port: Number(process.env.SMTP_PORT) || 587,
                secure: process.env.SMTP_SECURE === 'true',
                auth: {
                    user: process.env.SMTP_USER,
                    pass: process.env.SMTP_PASS
                }
            });
            console.log(`[Email Service] Custom SMTP configured (${process.env.SMTP_HOST})`);
        } else {
            // Ethereal Test Account (Zero Config, 100% Safe, Generates Web Preview Links)
            const testAccount = await nodemailer.createTestAccount();
            transporter = nodemailer.createTransport({
                host: 'smtp.ethereal.email',
                port: 587,
                secure: false,
                auth: {
                    user: testAccount.user,
                    pass: testAccount.pass
                }
            });
            console.log(`[Email Service] Ethereal Test Mailer initialized (${testAccount.user})`);
        }
    } catch (error) {
        console.error(`[Email Service Init Error]: ${error.message}`);
    }
};

const sendOrderConfirmationEmail = async (orderData) => {
    if (!transporter) {
        await initEmailTransporter();
    }

    const recipient = orderData.customerEmail || 'customer@example.com';
    const customerName = orderData.customerName || 'Valued Customer';
    const orderId = orderData.orderId;
    const totalAmount = orderData.totalAmount;
    const items = orderData.items || [];

    const itemsHtml = items.map(item => `
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #eeeeee;">${item.name}</td>
            <td style="padding: 10px; border-bottom: 1px solid #eeeeee; text-align: center;">${item.quantity}</td>
            <td style="padding: 10px; border-bottom: 1px solid #eeeeee; text-align: right;">$${Number(item.price).toFixed(2)}</td>
        </tr>
    `).join('');

    const htmlBody = `
        <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 580px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 12px; padding: 28px; background-color: #ffffff;">
            <div style="text-align: center; border-bottom: 2px solid #e91e63; padding-bottom: 16px;">
                <h1 style="color: #e91e63; margin: 0; font-size: 26px;">🎂 Cake Delight</h1>
                <p style="color: #666666; margin-top: 4px; font-size: 14px;">Order Confirmation & Receipt</p>
            </div>
            
            <div style="padding: 20px 0;">
                <h2 style="color: #333333; margin-top: 0;">Hello ${customerName},</h2>
                <p style="color: #555555; font-size: 15px; line-height: 1.5;">Thank you for your order! We are delighted to prepare your cake.</p>
                
                <div style="background-color: #fce4ec; border-radius: 8px; padding: 14px 18px; margin: 20px 0;">
                    <p style="margin: 4px 0; color: #880e4f;"><strong>Order ID:</strong> #${orderId}</p>
                    <p style="margin: 4px 0; color: #880e4f;"><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
                    <p style="margin: 4px 0; color: #880e4f;"><strong>Status:</strong> COMPLETED</p>
                </div>

                <h3 style="color: #333333;">Order Items</h3>
                <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
                    <thead>
                        <tr style="background-color: #f5f5f5;">
                            <th style="padding: 10px; text-align: left;">Item</th>
                            <th style="padding: 10px; text-align: center;">Qty</th>
                            <th style="padding: 10px; text-align: right;">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${itemsHtml}
                    </tbody>
                </table>

                <div style="text-align: right; font-size: 18px; color: #e91e63; padding-top: 10px;">
                    <strong>Total Amount: $${Number(totalAmount).toFixed(2)}</strong>
                </div>
            </div>

            <div style="border-top: 1px solid #eeeeee; padding-top: 16px; text-align: center; color: #888888; font-size: 12px;">
                <p>This email was automatically generated by the Cake Delight Notification Microservice.</p>
                <p>&copy; ${new Date().getFullYear()} Cake Delight Microservices Application</p>
            </div>
        </div>
    `;

    try {
        const mailOptions = {
            from: '"Cake Delight Orders" <orders@cakedelight.com>',
            to: recipient,
            subject: `🎂 Order Confirmation #${String(orderId).substring(0, 8)} - Cake Delight`,
            html: htmlBody
        };

        const info = await transporter.sendMail(mailOptions);
        const previewUrl = nodemailer.getTestMessageUrl(info);

        console.log(`[Email Sent] Message ID: ${info.messageId}`);
        if (previewUrl) {
            console.log(`[Ethereal Live Email Preview URL]: ${previewUrl}`);
        }

        return {
            success: true,
            messageId: info.messageId,
            previewUrl: previewUrl || null
        };
    } catch (error) {
        console.error(`[Email Send Error]: ${error.message}`);
        return { success: false, error: error.message };
    }
};

module.exports = {
    initEmailTransporter,
    sendOrderConfirmationEmail
};
